/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2017-02-09 17:13:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ms.framework.util.Config;
import java.util.*;
import com.ms.framework.util.Config;
import com.hxh.shop.common.util.UserContext;

public final class countryHistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/tags/base.tld", Long.valueOf(1471439204000L));
    _jspx_dependants.put("/WEB-INF/tags/h5.tld", Long.valueOf(1471439204000L));
    _jspx_dependants.put("/WEB-INF/jsp/goods/../pub/head.inc", Long.valueOf(1486632866000L));
    _jspx_dependants.put("/WEB-INF/tags/c.tld", Long.valueOf(1471439204000L));
    _jspx_dependants.put("/WEB-INF/jsp/goods/../pub/tags.inc", Long.valueOf(1471439204000L));
    _jspx_dependants.put("/WEB-INF/jsp/goods/../pub/footerNavigation.jsp", Long.valueOf(1477994420000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');

    request.setAttribute("version","2.5");
    request.setAttribute("STATIC_SERVER", Config.getValue("uploadDomain"));
    request.setAttribute("DOMAIN",Config.getValue("domain"));

      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=0\"/>\r\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\"/>\r\n");
      out.write("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\"/>\r\n");
      out.write("<meta name=\"format-detection\" content=\"email=no\"/>\r\n");
      out.write("<link href=\"/css/effect.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/base.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"/css/xhw.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\"/>\r\n");
      out.write("<link href=\"/css/mycenter.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\"/>\r\n");
      out.write("<script src=\"/js/jquery.js?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("<script src=\"/js/base-util.js?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=0\" />\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("    <meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("    <meta name=\"format-detection\" content=\"email=no\" />\r\n");
      out.write("    <title>乡间直供</title>\r\n");
      out.write("    <link href=\"/css/common.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"/css/xjzg.css?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" rel=\"stylesheet\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/resize.js\"></script>\r\n");
      out.write("    <script src=\"/js/h5base.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        @media screen and (max-width:359px) {\r\n");
      out.write("            #footer a dd  {\r\n");
      out.write("                font-size:10px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @media screen and (min-width: 360px) and (max-width:399px){\r\n");
      out.write("            #footer  a dd{\r\n");
      out.write("                font-size:12px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @media screen and (min-width: 400px) and (max-width:479px){\r\n");
      out.write("            #footer a dd {\r\n");
      out.write("                font-size:14px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @media screen and (min-width: 480px) and (max-width:519px){\r\n");
      out.write("            #footer a dd {\r\n");
      out.write("                font-size:16px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        @media screen and (min-width:520px){\r\n");
      out.write("            #footer a dd {\r\n");
      out.write("                font-size:18px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        var oldOrderByflag = \"0\";       //老的排序方式，用于与新的排序方式比较是否发生变化\r\n");
      out.write("        var cateType = \"\";\r\n");
      out.write("        var cateTypeSub = \"\";\r\n");
      out.write("        var buttonLength = 0;\r\n");
      out.write("        var curPage = 1;\r\n");
      out.write("        var pageSize = 10;\r\n");
      out.write("        var index = 0;\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            checkTheGoods(\"5\", '1');\r\n");
      out.write("        });\r\n");
      out.write("        function checkTheGoods(orderByFlag, click) {\r\n");
      out.write("            changeOrderBy(orderByFlag, click);\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                dataType: \"json\", //数据格式:JSON\r\n");
      out.write("                contenttype: \"application/x-www-form-urlencoded;charset=utf-8\",\r\n");
      out.write("                type: \"POST\", //用POST方式传输\r\n");
      out.write("                url: '/ajaxSearchCountryDirectJson.do', //目标地址\r\n");
      out.write("                data: {'nactivity_category_id':\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nactivity_category_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",'orderByFlag':oldOrderByflag,'pageSize':pageSize,'curPage':curPage},\r\n");
      out.write("                success: function (data) {\r\n");
      out.write("                    var goodsObj = eval(\"(\" + data + \")\");\r\n");
      out.write("                    if(goodsObj[0].goodsList.length > 0) {\r\n");
      out.write("                        var goodObj = goodsObj[0].goodsList;\r\n");
      out.write("                        var divValue = \"\";\r\n");
      out.write("                        for(var i in goodObj) {\r\n");
      out.write("                            var divValu = $(\"#oneGoodInfoDiv\").html();\r\n");
      out.write("                            divValu = divValu.replace(\"vname\", goodObj[i].vname);\r\n");
      out.write("                            divValu = divValu.replace(\"nowpic\", formatNumber(goodObj[i].nprice, \"#.00\"));\r\n");
      out.write("                            divValu = divValu.replace(\"goodsImgUrl\", goodObj[i].vimage==null?'':'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${STATIC_SERVER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("' + goodObj[i].vimage);\r\n");
      out.write("                            divValu = divValu.replace(\"vend_time\", goodObj[i].vend_time.substring(0, 4) + \"-\" + goodObj[i].vend_time.substring(4, 6) + \"-\" + goodObj[i].vend_time.substring(6, 8));\r\n");
      out.write("                            divValu = divValu.replace(\"nconcern_nums\", goodObj[i].nconcern_nums);\r\n");
      out.write("                            divValu = divValu.replace(\"outNum\", goodObj[i].YFKNum);\r\n");
      out.write("                            divValu = divValu.replace(\"nactivityId1\", \"nactivity_id=\"+goodObj[i].nactivity_id);\r\n");
      out.write("                            divValu = divValu.replace(\"nactivityId2\", \"nactivity_id=\"+goodObj[i].nactivity_id);\r\n");
      out.write("                            index = index + 1;\r\n");
      out.write("                            divValue += divValu;\r\n");
      out.write("                        }\r\n");
      out.write("                        $(\"#goodsListDiv\").append(divValue);\r\n");
      out.write("                        curPage += 1;\r\n");
      out.write("                    }else{\r\n");
      out.write("                        if($(\"#goodsListDiv\").children().size()==0) {\r\n");
      out.write("                            var divValu = $(\"#noSeach\").html();\r\n");
      out.write("                            $(\"#goodsListDiv\").append(divValu);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function changeOrderBy(orderByFlag, click) {\r\n");
      out.write("            if(click == \"1\") {\r\n");
      out.write("                curPage = 1;\r\n");
      out.write("                $(\"#goodsListDiv\").html('');\r\n");
      out.write("                if (oldOrderByflag != orderByFlag) {\r\n");
      out.write("                    oldOrderByflag = orderByFlag;\r\n");
      out.write("                } else {\r\n");
      out.write("                    orderByFlag = parseInt(orderByFlag) + 1;\r\n");
      out.write("                    oldOrderByflag = orderByFlag;\r\n");
      out.write("                }\r\n");
      out.write("                $(\"#goodSpanId\").removeClass();\r\n");
      out.write("                $(\"#saleSpanId\").removeClass();\r\n");
      out.write("                $(\"#picSpanId\").removeClass();\r\n");
      out.write("                if(oldOrderByflag == 1) {\r\n");
      out.write("                    $(\"#goodSpanId\").addClass(\"act\");\r\n");
      out.write("                    $(\"#goodSpanId\").find(\"span\").attr(\"class\",\"icon\");\r\n");
      out.write("                } else if(oldOrderByflag == 2) {\r\n");
      out.write("                    $(\"#goodSpanId\").addClass(\"act2\");\r\n");
      out.write("                    $(\"#goodSpanId\").find(\"span\").attr(\"class\",\"icon2\");\r\n");
      out.write("                } else if(oldOrderByflag == 3) {\r\n");
      out.write("                    $(\"#saleSpanId\").addClass(\"act\");\r\n");
      out.write("                    $(\"#saleSpanId\").find(\"span\").attr(\"class\",\"icon\");\r\n");
      out.write("                } else if(oldOrderByflag == 4) {\r\n");
      out.write("                    $(\"#saleSpanId\").addClass(\"act2\");\r\n");
      out.write("                    $(\"#saleSpanId\").find(\"span\").attr(\"class\",\"icon2\");\r\n");
      out.write("                } else if(oldOrderByflag == 5) {\r\n");
      out.write("                    $(\"#picSpanId\").addClass(\"act\");\r\n");
      out.write("                    $(\"#picSpanId\").find(\"span\").attr(\"class\",\"icon\");\r\n");
      out.write("                } else if(oldOrderByflag == 6) {\r\n");
      out.write("                    $(\"#picSpanId\").addClass(\"act2\");\r\n");
      out.write("                    $(\"#picSpanId\").find(\"span\").attr(\"class\",\"icon2\");\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        $(window).scroll(function () {\r\n");
      out.write("            if ($(window).scrollTop() == $(document).height() - $(window).height()) {\r\n");
      out.write("                checkTheGoods(oldOrderByflag, '0');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--主体开始-->\r\n");
      out.write("<div class=\"xjzg_box pd525\">\r\n");
      out.write("    <div class=\"tab arrowdiv\">\r\n");
      out.write("        <ul>\r\n");
      out.write("           <li><a href=\"/home/country.do?loadingfadeOut=0\">进行中</a></li>\r\n");
      out.write("           <li class=\"act\"><span><i></i></span>往期</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"write_bg\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <nav class=\"fenleiss\">\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      <a href=\"/home/countryHistory.do\"><dl>\r\n");
      out.write("         <dt class=\"ico_out8\"></dt>\r\n");
      out.write("         <dd>全部</dd>\r\n");
      out.write("     </dl></a>\r\n");
      out.write("   <p class=\"clear\"></p>\r\n");
      out.write("\r\n");
      out.write("  </nav>\r\n");
      out.write("   \r\n");
      out.write("    <div class=\"h1rem\"></div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     <div id=\"ranking\" class=\"ranking\" >\r\n");
      out.write("      <ul>\r\n");
      out.write("          <li onclick=\"checkTheGoods('1', '1');\" id=\"goodSpanId\">销量 <span class=\"icon\"></span> </li>\r\n");
      out.write("          <li onclick=\"checkTheGoods('3', '1');\" id=\"saleSpanId\">关注<span class=\"icon\"></span></li>\r\n");
      out.write("          <li onclick=\"checkTheGoods('5', '1');\" id=\"picSpanId\">时间<span class=\"icon\"></span></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"oneGoodInfoDiv\" style=\"display: none\">\r\n");
      out.write("        <div class=\"wq_list\">\r\n");
      out.write("            <div class=\"image\"><span class=\"ended\"></span>\r\n");
      out.write("                <span class=\"guanzhu\"><span class=\"guanzhu_icon\"></span>nconcern_nums</span>\r\n");
      out.write("                <a href=\"/home/countryDetail.do?nactivityId1\"><img src=\"goodsImgUrl\"  style=\"height: 200px;\" width=\"100%\" alt=\"\"/></a></div>\r\n");
      out.write("            <div class=\"title\"><span class=\"price\"><i>￥</i>nowpic</span><a href=\"/home/countryDetail.do?nactivityId2\">vname</a> </div>\r\n");
      out.write("            <div class=\"other\"><span class=\"date\">vend_time</span> outNum人已购买 </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"noSeach\"  style=\"display: none\">\r\n");
      out.write("        <div  class=\"zanwuhuodong_bg\">\r\n");
      out.write("            <dl class=\"jqqd\">\r\n");
      out.write("                <dd>未发现乡间直供！</dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <div class=\"common_wrappers\">\r\n");
      out.write("      <div class=\"h2rem\"></div>\r\n");
      out.write("       <div id=\"goodsListDiv\" class=\"wq_box\">\r\n");
      out.write("       </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!--主体结束-->\r\n");
      out.write("\r\n");
      out.write("<!--底部-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--弹出层二级菜单-->\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String m_domain= Config.getValue("js-cross-domain");
  request.setAttribute("m_domain",m_domain);
  request.setAttribute("shopId", UserContext.getSellShopId());
  if("10000001".equals(UserContext.getSellShopId())){
    request.setAttribute("shopId", "m");
  }

      out.write("\r\n");
      out.write("<!--主体结束-->\r\n");
      out.write("<div class=\"h10\"></div>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <a ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(" href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/shop/home.do?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&scene=4#wechat_redirect\">\r\n");
      out.write("    <dl >\r\n");
      out.write("      <dt class=\"ico ico_mall\"></dt>\r\n");
      out.write("      <dd>平价商城</dd>\r\n");
      out.write("    </dl></a>\r\n");
      out.write("\r\n");
      out.write("    <a ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("  href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/home/country.do?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&scene=4#wechat_redirect\">\r\n");
      out.write("      <dl>\r\n");
      out.write("        <dt class=\"ico ico_home\"></dt>\r\n");
      out.write("        <dd>乡间直供</dd>\r\n");
      out.write("      </dl></a>\r\n");
      out.write("\r\n");
      out.write("  <a  ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write(" href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/showMyNear.do?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&scene=4#wechat_redirect\">\r\n");
      out.write("    <dl>\r\n");
      out.write("      <dt class=\"ico ico_fujin\"></dt>\r\n");
      out.write("      <dd>线下门店</dd>\r\n");
      out.write("    </dl></a>\r\n");
      out.write("\r\n");
      out.write("  <a  ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" href=\"http://");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${shopId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('.');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${m_domain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/center.do?t=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("&scene=4#wechat_redirect\" >");
      out.write("\r\n");
      out.write("    <dl>\r\n");
      out.write("      <dt class=\"ico ico_wo\"></dt>\r\n");
      out.write("      <dd>我的乡货</dd>\r\n");
      out.write("    </dl></a>\r\n");
      out.write("</footer>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://pingjs.qq.com/h5/stats.js\" name=\"MTAH5\" sid=\"500001265\" ></script>\r\n");
      out.write("<!--底部-->\r\n");
      out.write("\r\n");
      out.write("<!--底部-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  $(function(){  \r\n");
      out.write("  var navH = $(\"#ranking\").offset().top;  \r\n");
      out.write("  console.log('navH--->'+navH);\r\n");
      out.write("  $(window).scroll(function(){  \r\n");
      out.write("  var scroH = $(this).scrollTop();  \r\n");
      out.write("  console.log('scroH---->'+scroH);\r\n");
      out.write("   if(scroH>=navH){  \r\n");
      out.write("\t  $(\"#ranking\").css({\"position\":\"fixed\",\"top\":0});   \r\n");
      out.write("\t  }else if(scroH<navH){   \r\n");
      out.write("\t\t  $(\"#ranking\").css({\"position\":\"static\"}); \r\n");
      out.write("\t  }  \r\n");
      out.write("\t  })  \r\n");
      out.write("   })  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/goods/countryHistory.jsp(155,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/jsp/goods/countryHistory.jsp(155,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("result");
    // /WEB-INF/jsp/goods/countryHistory.jsp(155,4) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("id");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          <a href=\"/home/countryHistory.do?nactivity_category_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result.nactivity_category_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"><dl>\r\n");
          out.write("             <dt class=\"ico_out");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id.index+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\"></dt>\r\n");
          out.write("             <dd>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${result.vname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</dd>\r\n");
          out.write("         </dl></a>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/goods/../pub/footerNavigation.jsp(28,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.homeFooterAtc=='2'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"act\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/goods/../pub/footerNavigation.jsp(34,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.homeFooterAtc=='1'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"act\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/jsp/goods/../pub/footerNavigation.jsp(40,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.homeFooterAtc=='3'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"act\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/jsp/goods/../pub/footerNavigation.jsp(46,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.homeFooterAtc=='4'}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("class=\"act\"");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }
}
